# Generated by Django 4.2.1 on 2023-10-06 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_Main_Img_URL',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
